// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SalesAnalysis;

#nullable disable

namespace SalesAnalisys.Migrations
{
    [DbContext(typeof(SalesAnalysisContext))]
    [Migration("20231226190009_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SalesAnalysis.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cluster")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<double>("Total")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cluster = 3,
                            Name = "Мягкая игрушка",
                            Price = 35000.0,
                            Total = 16.0
                        },
                        new
                        {
                            Id = 2,
                            Cluster = 3,
                            Name = "Косметичка",
                            Price = 22000.0,
                            Total = 21.0
                        },
                        new
                        {
                            Id = 3,
                            Cluster = 2,
                            Name = "Скатерть",
                            Price = 24000.0,
                            Total = 38.0
                        },
                        new
                        {
                            Id = 4,
                            Cluster = 1,
                            Name = "Рюкзак",
                            Price = 63000.0,
                            Total = 20.0
                        },
                        new
                        {
                            Id = 5,
                            Cluster = 0,
                            Name = "Подставка для телефона",
                            Price = 40000.0,
                            Total = 46.0
                        },
                        new
                        {
                            Id = 6,
                            Cluster = 0,
                            Name = "Зажигалка",
                            Price = 32000.0,
                            Total = 35.0
                        },
                        new
                        {
                            Id = 7,
                            Cluster = 0,
                            Name = "Радио",
                            Price = 42000.0,
                            Total = 33.0
                        },
                        new
                        {
                            Id = 8,
                            Cluster = 3,
                            Name = "Гель для душа",
                            Price = 17000.0,
                            Total = 3.0
                        },
                        new
                        {
                            Id = 9,
                            Cluster = 2,
                            Name = "Ножницы",
                            Price = 21000.0,
                            Total = 27.0
                        },
                        new
                        {
                            Id = 10,
                            Cluster = 2,
                            Name = "Кольцо",
                            Price = 34000.0,
                            Total = 47.0
                        },
                        new
                        {
                            Id = 11,
                            Cluster = 1,
                            Name = "Серьги",
                            Price = 44000.0,
                            Total = 20.0
                        },
                        new
                        {
                            Id = 12,
                            Cluster = 2,
                            Name = "Ботинки",
                            Price = 30000.0,
                            Total = 45.0
                        },
                        new
                        {
                            Id = 13,
                            Cluster = 1,
                            Name = "Колонка",
                            Price = 60000.0,
                            Total = 10.0
                        },
                        new
                        {
                            Id = 14,
                            Cluster = 2,
                            Name = "Свитер",
                            Price = 15000.0,
                            Total = 22.0
                        },
                        new
                        {
                            Id = 15,
                            Cluster = 2,
                            Name = "Вешалка",
                            Price = 23000.0,
                            Total = 25.0
                        },
                        new
                        {
                            Id = 16,
                            Cluster = 2,
                            Name = "Лампа",
                            Price = 17000.0,
                            Total = 32.0
                        },
                        new
                        {
                            Id = 17,
                            Cluster = 3,
                            Name = "Шоколадка",
                            Price = 40000.0,
                            Total = 18.0
                        },
                        new
                        {
                            Id = 18,
                            Cluster = 3,
                            Name = "Молоток",
                            Price = 28000.0,
                            Total = 15.0
                        },
                        new
                        {
                            Id = 19,
                            Cluster = 1,
                            Name = "Краска для волос",
                            Price = 54000.0,
                            Total = 18.0
                        },
                        new
                        {
                            Id = 20,
                            Cluster = 2,
                            Name = "Печка",
                            Price = 23000.0,
                            Total = 26.0
                        },
                        new
                        {
                            Id = 21,
                            Cluster = 0,
                            Name = "Пенал",
                            Price = 40000.0,
                            Total = 59.0
                        },
                        new
                        {
                            Id = 22,
                            Cluster = 3,
                            Name = "Письменный стол",
                            Price = 31000.0,
                            Total = 34.0
                        },
                        new
                        {
                            Id = 23,
                            Cluster = 3,
                            Name = "Кастрюля",
                            Price = 18000.0,
                            Total = 14.0
                        },
                        new
                        {
                            Id = 24,
                            Cluster = 0,
                            Name = "Футбольный мяч",
                            Price = 38000.0,
                            Total = 47.0
                        },
                        new
                        {
                            Id = 25,
                            Cluster = 1,
                            Name = "Пальто",
                            Price = 57000.0,
                            Total = 23.0
                        },
                        new
                        {
                            Id = 26,
                            Cluster = 3,
                            Name = "Фонарик",
                            Price = 34000.0,
                            Total = 15.0
                        },
                        new
                        {
                            Id = 27,
                            Cluster = 1,
                            Name = "Костюм",
                            Price = 46000.0,
                            Total = 5.0
                        },
                        new
                        {
                            Id = 28,
                            Cluster = 3,
                            Name = "Компьютерная мышь",
                            Price = 23000.0,
                            Total = 8.0
                        },
                        new
                        {
                            Id = 29,
                            Cluster = 2,
                            Name = "Вино",
                            Price = 16000.0,
                            Total = 19.0
                        },
                        new
                        {
                            Id = 30,
                            Cluster = 3,
                            Name = "Столешница",
                            Price = 23000.0,
                            Total = 16.0
                        },
                        new
                        {
                            Id = 31,
                            Cluster = 1,
                            Name = "Печь",
                            Price = 46000.0,
                            Total = 13.0
                        },
                        new
                        {
                            Id = 32,
                            Cluster = 1,
                            Name = "Кольцо",
                            Price = 53000.0,
                            Total = 12.0
                        },
                        new
                        {
                            Id = 33,
                            Cluster = 1,
                            Name = "Журнал",
                            Price = 62000.0,
                            Total = 35.0
                        },
                        new
                        {
                            Id = 34,
                            Cluster = 1,
                            Name = "Спортивные штаны",
                            Price = 55000.0,
                            Total = 1.0
                        },
                        new
                        {
                            Id = 35,
                            Cluster = 2,
                            Name = "Детская книга",
                            Price = 35000.0,
                            Total = 47.0
                        },
                        new
                        {
                            Id = 36,
                            Cluster = 2,
                            Name = "Зубная щетка",
                            Price = 15000.0,
                            Total = 29.0
                        },
                        new
                        {
                            Id = 37,
                            Cluster = 0,
                            Name = "Мыло",
                            Price = 43000.0,
                            Total = 45.0
                        },
                        new
                        {
                            Id = 38,
                            Cluster = 1,
                            Name = "Бейсболка",
                            Price = 42000.0,
                            Total = 15.0
                        },
                        new
                        {
                            Id = 39,
                            Cluster = 3,
                            Name = "Телефон",
                            Price = 33000.0,
                            Total = 10.0
                        },
                        new
                        {
                            Id = 40,
                            Cluster = 3,
                            Name = "Паззл",
                            Price = 29000.0,
                            Total = 22.0
                        },
                        new
                        {
                            Id = 41,
                            Cluster = 3,
                            Name = "Зонт",
                            Price = 17000.0,
                            Total = 6.0
                        },
                        new
                        {
                            Id = 42,
                            Cluster = 2,
                            Name = "Гитара",
                            Price = 26000.0,
                            Total = 29.0
                        },
                        new
                        {
                            Id = 43,
                            Cluster = 3,
                            Name = "Фляга",
                            Price = 31000.0,
                            Total = 21.0
                        },
                        new
                        {
                            Id = 44,
                            Cluster = 3,
                            Name = "Туфли",
                            Price = 20000.0,
                            Total = 12.0
                        },
                        new
                        {
                            Id = 45,
                            Cluster = 3,
                            Name = "Майка",
                            Price = 18000.0,
                            Total = 10.0
                        },
                        new
                        {
                            Id = 46,
                            Cluster = 1,
                            Name = "Халат",
                            Price = 55000.0,
                            Total = 44.0
                        },
                        new
                        {
                            Id = 47,
                            Cluster = 0,
                            Name = "Скатерть",
                            Price = 42000.0,
                            Total = 26.0
                        },
                        new
                        {
                            Id = 48,
                            Cluster = 0,
                            Name = "Сумка для ноутбука",
                            Price = 51000.0,
                            Total = 49.0
                        },
                        new
                        {
                            Id = 49,
                            Cluster = 3,
                            Name = "Часы",
                            Price = 33000.0,
                            Total = 31.0
                        },
                        new
                        {
                            Id = 50,
                            Cluster = 1,
                            Name = "Шоколад",
                            Price = 44000.0,
                            Total = 12.0
                        },
                        new
                        {
                            Id = 51,
                            Cluster = 1,
                            Name = "Косилка",
                            Price = 44000.0,
                            Total = 7.0
                        },
                        new
                        {
                            Id = 52,
                            Cluster = 1,
                            Name = "Пыльца",
                            Price = 42000.0,
                            Total = 5.0
                        },
                        new
                        {
                            Id = 53,
                            Cluster = 2,
                            Name = "Рамка для фото",
                            Price = 21000.0,
                            Total = 21.0
                        },
                        new
                        {
                            Id = 54,
                            Cluster = 2,
                            Name = "Термос",
                            Price = 20000.0,
                            Total = 29.0
                        },
                        new
                        {
                            Id = 55,
                            Cluster = 1,
                            Name = "Пылесос",
                            Price = 49000.0,
                            Total = 2.0
                        },
                        new
                        {
                            Id = 56,
                            Cluster = 1,
                            Name = "Ветровка",
                            Price = 56000.0,
                            Total = 39.0
                        },
                        new
                        {
                            Id = 57,
                            Cluster = 2,
                            Name = "Спальный мешок",
                            Price = 25000.0,
                            Total = 48.0
                        },
                        new
                        {
                            Id = 58,
                            Cluster = 2,
                            Name = "Пианино",
                            Price = 22000.0,
                            Total = 28.0
                        },
                        new
                        {
                            Id = 59,
                            Cluster = 1,
                            Name = "Сапоги",
                            Price = 54000.0,
                            Total = 16.0
                        },
                        new
                        {
                            Id = 60,
                            Cluster = 0,
                            Name = "Косметичка",
                            Price = 40000.0,
                            Total = 43.0
                        },
                        new
                        {
                            Id = 61,
                            Cluster = 2,
                            Name = "Зеркало",
                            Price = 16000.0,
                            Total = 31.0
                        },
                        new
                        {
                            Id = 62,
                            Cluster = 1,
                            Name = "Подставка для ноутбука",
                            Price = 62000.0,
                            Total = 32.0
                        },
                        new
                        {
                            Id = 63,
                            Cluster = 2,
                            Name = "Мяч",
                            Price = 20000.0,
                            Total = 21.0
                        },
                        new
                        {
                            Id = 64,
                            Cluster = 1,
                            Name = "Подушка",
                            Price = 45000.0,
                            Total = 12.0
                        },
                        new
                        {
                            Id = 65,
                            Cluster = 0,
                            Name = "Очки",
                            Price = 43000.0,
                            Total = 27.0
                        },
                        new
                        {
                            Id = 66,
                            Cluster = 2,
                            Name = "Сумка",
                            Price = 15000.0,
                            Total = 31.0
                        },
                        new
                        {
                            Id = 67,
                            Cluster = 2,
                            Name = "Браслет",
                            Price = 30000.0,
                            Total = 49.0
                        },
                        new
                        {
                            Id = 68,
                            Cluster = 3,
                            Name = "Кружка",
                            Price = 24000.0,
                            Total = 5.0
                        },
                        new
                        {
                            Id = 69,
                            Cluster = 0,
                            Name = "Сковорода",
                            Price = 51000.0,
                            Total = 40.0
                        },
                        new
                        {
                            Id = 70,
                            Cluster = 2,
                            Name = "Коврик для йоги",
                            Price = 35000.0,
                            Total = 52.0
                        },
                        new
                        {
                            Id = 71,
                            Cluster = 1,
                            Name = "Печка",
                            Price = 55000.0,
                            Total = 24.0
                        },
                        new
                        {
                            Id = 72,
                            Cluster = 3,
                            Name = "Зонтик",
                            Price = 35000.0,
                            Total = 27.0
                        },
                        new
                        {
                            Id = 73,
                            Cluster = 3,
                            Name = "Подушка",
                            Price = 28000.0,
                            Total = 28.0
                        },
                        new
                        {
                            Id = 74,
                            Cluster = 3,
                            Name = "Шапка",
                            Price = 20000.0,
                            Total = 17.0
                        },
                        new
                        {
                            Id = 75,
                            Cluster = 2,
                            Name = "Велосипед",
                            Price = 15000.0,
                            Total = 23.0
                        },
                        new
                        {
                            Id = 76,
                            Cluster = 1,
                            Name = "Пазл",
                            Price = 59000.0,
                            Total = 38.0
                        },
                        new
                        {
                            Id = 77,
                            Cluster = 3,
                            Name = "Пижама",
                            Price = 23000.0,
                            Total = 1.0
                        },
                        new
                        {
                            Id = 78,
                            Cluster = 2,
                            Name = "Платье",
                            Price = 28000.0,
                            Total = 52.0
                        },
                        new
                        {
                            Id = 79,
                            Cluster = 3,
                            Name = "Клавиатура",
                            Price = 28000.0,
                            Total = 9.0
                        },
                        new
                        {
                            Id = 80,
                            Cluster = 1,
                            Name = "Мышь",
                            Price = 55000.0,
                            Total = 2.0
                        },
                        new
                        {
                            Id = 81,
                            Cluster = 1,
                            Name = "Скейтборд",
                            Price = 55000.0,
                            Total = 7.0
                        },
                        new
                        {
                            Id = 82,
                            Cluster = 0,
                            Name = "Светильник",
                            Price = 45000.0,
                            Total = 29.0
                        },
                        new
                        {
                            Id = 83,
                            Cluster = 3,
                            Name = "Ковер",
                            Price = 22000.0,
                            Total = 10.0
                        },
                        new
                        {
                            Id = 84,
                            Cluster = 0,
                            Name = "Книжная полка",
                            Price = 40000.0,
                            Total = 49.0
                        },
                        new
                        {
                            Id = 85,
                            Cluster = 0,
                            Name = "Рюкзак",
                            Price = 41000.0,
                            Total = 37.0
                        },
                        new
                        {
                            Id = 86,
                            Cluster = 3,
                            Name = "Джинсы",
                            Price = 16000.0,
                            Total = 1.0
                        },
                        new
                        {
                            Id = 87,
                            Cluster = 1,
                            Name = "Футболка",
                            Price = 52000.0,
                            Total = 12.0
                        },
                        new
                        {
                            Id = 88,
                            Cluster = 2,
                            Name = "Кресло",
                            Price = 23000.0,
                            Total = 28.0
                        },
                        new
                        {
                            Id = 89,
                            Cluster = 1,
                            Name = "Стол",
                            Price = 54000.0,
                            Total = 18.0
                        },
                        new
                        {
                            Id = 90,
                            Cluster = 0,
                            Name = "Чайник",
                            Price = 49000.0,
                            Total = 58.0
                        },
                        new
                        {
                            Id = 91,
                            Cluster = 2,
                            Name = "Кроссовки",
                            Price = 21000.0,
                            Total = 31.0
                        },
                        new
                        {
                            Id = 92,
                            Cluster = 3,
                            Name = "Шарф",
                            Price = 24000.0,
                            Total = 22.0
                        },
                        new
                        {
                            Id = 93,
                            Cluster = 1,
                            Name = "Наушники",
                            Price = 65000.0,
                            Total = 13.0
                        },
                        new
                        {
                            Id = 94,
                            Cluster = 1,
                            Name = "Планшет",
                            Price = 64000.0,
                            Total = 48.0
                        },
                        new
                        {
                            Id = 95,
                            Cluster = 1,
                            Name = "Кофеварка",
                            Price = 40000.0,
                            Total = 1.0
                        },
                        new
                        {
                            Id = 96,
                            Cluster = 3,
                            Name = "Фитнес-трекер",
                            Price = 22000.0,
                            Total = 13.0
                        },
                        new
                        {
                            Id = 97,
                            Cluster = 2,
                            Name = "Смартфон",
                            Price = 19000.0,
                            Total = 18.0
                        },
                        new
                        {
                            Id = 98,
                            Cluster = 1,
                            Name = "Ноутбук",
                            Price = 50000.0,
                            Total = 19.0
                        },
                        new
                        {
                            Id = 99,
                            Cluster = 3,
                            Name = "Фотоаппарат",
                            Price = 31000.0,
                            Total = 33.0
                        },
                        new
                        {
                            Id = 100,
                            Cluster = 1,
                            Name = "Книга",
                            Price = 48000.0,
                            Total = 22.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
